Exercise1
Systems-Development-and-Frameworks/SCP-Foundation pull request #2
Opened 2020-10-16 14:16 UTC by MatzeK105

Finished exercise 1:
- project setup
- implemented list view
- add and remove comments
- upvote and downvote comments
- comments sorted by score in descending order

Updated READMEs

2020-10-19 09:57 UTC, medizinmensch commented
You got 5 stars in the review below. Furthermore:

* you pulled the new exercises :star: 
* clean responsibilities :star: 
* your PR does not contain unrelated changes :star: 
* could not find any runtime errors :star: 

Thus, you currently have **9 out of 10 stars**.

Where I can not yet give you a point is for **using functional paradigms**. You rather used object an object oriented approach (which can also be fine, but wasn't the task here). You still have a change until next week to change a bit here. 
But maybe @roschaefer is already fine with the implementation like this.

Apart from the points:

What's nice:
What I really appreciate is that you updated your README.md with a how to use and contributors! Very nice!

Room for improvement though:

I prefer having the install/run instructions of the web all at one place only (you have it at `./README.md` and `./weapp/sdf/README.md`). I like it in the `README.md`.

2020-10-19 11:00 UTC, roschaefer requested changes
Totally agree with what @medizinmensch already reviewed, plus the suggestions below :point_down:

2020-10-19 11:00 UTC, roschaefer commented on exercises/1/README.md
> +Due date: **28.09.2020**
Please update with latest changes: https://github.com/Systems-Development-and-Frameworks/homework/commit/7c99c70634082dcc4579b9622762cb097770ff49

You should "watch" the origin repository as explained in the [README.md](https://github.com/Systems-Development-and-Frameworks/homework#how-to-submit-homework)

![watch repo](https://raw.githubusercontent.com/Systems-Development-and-Frameworks/homework/main/.github/img/watch_repo.png)

2020-10-19 11:00 UTC, roschaefer commented on webapp/sdf/src/components/item-component.vue
> +    removeItem: function (_item) {
```suggestion
    removeItem(_item) {
```

Use shorthand: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#Description

2020-10-19 11:00 UTC, roschaefer commented on webapp/sdf/src/components/item-component.vue
> +    updateItem: function (_item, value) {
```suggestion
    updateItem: function (item, value) {
```
Using _underscore prefix for an argument is a naming convention when you don't use the argument in the function body, but you *do use* it on line 23. Other naming conventions use underscores to indicate private methods/properties. But that doesn't seem to be the case here. See: https://eslint.org/docs/rules/no-underscore-dangle

2020-10-19 11:00 UTC, roschaefer commented on webapp/sdf/src/components/list-component.vue
> +      });
```suggestion
      return newArray.sort((a, b) => b.votes - a.votes);
```

2020-10-19 11:00 UTC, roschaefer commented on webapp/sdf/src/components/list-component.vue
> +      this.itemList[index].votes += value;
This is not very clean with regards to responsibilities. The list component shouldn't know the internals of an `item`. Instead, you should have a immutable, unique property `id` on the item. Then, list-component can just do:
```js
this.itemList = this.itemList.map((i) => i.id === item.id ? item : i)
```

2020-10-19 11:00 UTC, roschaefer commented on webapp/sdf/src/components/list-component.vue
> +        v-bind:item="item"
```suggestion
        :item="item"
```
Use shorthand

2020-10-19 11:00 UTC, roschaefer commented on webapp/sdf/src/components/list-component.vue
> +    </div>
This could be another component.

2020-10-19 11:00 UTC, roschaefer commented on webapp/sdf/src/components/item-component.vue
> +    <button v-on:click="removeItem(item)">Remove</button>
```suggestion
    <button @click="removeItem(item)">Remove</button>
```
Use shorthand

2020-10-30 15:14 UTC, medizinmensch commented
I saw you improved by using `filter` instead of splice/index. Good example for functional programming!

You now got 10/10 ⭐

2020-11-09 14:20 UTC, merged